### ISSUE TITLE
输入框的内容,回车输出就是空白

### ISSUE THREAD

**Issue by angelbaba** [Unintendedz/talk-to-gpt-4-mobile#1]
请问下,这个要怎么设置呀,请大佬抽空帮忙看下

**Comment by angelbaba** [comment]
> 请问下,这个要怎么设置呀,请大佬抽空帮忙看下

![image](https://github.com/Unintendedz/talk-to-gpt-4-mobile/assets/45415907/9a655fde-faae-4a08-87f6-3bf968903830)

**Comment by Unintendedz** [comment]
嗨，@angelbaba。
我的脚本只是修改了请求模型列表的 API 的响应，来让 web 界面自行展示出 gpt-4-mobile 模型按钮。
所以发送文本变成空白的问题不太可能是由这个脚本引起的。

但我从你提供的截图中看出你似乎安装了其它的插件或者脚本，也许有某个脚本或者插件与我的脚本产生了冲突。

你可否试试：
1. 只启用我的脚本，是否会出现这个问题？如果会，请换个全新的浏览器试试，还会吗？
2. 如果只启用我的脚本没有出现这个问题，那么在启用我的脚本的前提下启用其它哪个插件或脚本会造成这个问题呢？

**Comment by Unintendedz** [comment]
鉴于该 issue 已经很长时间无人回复，我将关闭它。如果仍有问题的话，欢迎随时再打开。
