### ISSUE TITLE
我拷贝了你的代码

### ISSUE THREAD

**Issue by onepisYa** [Unintendedz/talk-to-gpt-4-mobile#2]
https://greasyfork.org/en/scripts/467802-gpt-4-mobile  这个是油猴脚本的地址，我写了文档，以及把你的脚本和另外一个脚本结合起来了，但是我也没想到， 2天不到直接 干到 1800 多下载量了。然后那个人 也许是看不惯？不知道怎么想的，就来评论区叨叨，又没有逻辑，文档也不看，不过我的代码 90% 确实是copy 的你和另外一个老哥的，所以你给个授权？还是啥？

就是也在你评论区评论了的那个人  Script does not work, no model is "unlimited", be careful do not believe the sneaky author! 这个是他的 Github， https://github.com/adamlui  。

本来也没有想那么多，仅仅只是两个脚本变一个方便一点，并不想要下载那么多脚本。看到了回复下哈，兄弟。

**Comment by Unintendedz** [comment]
好的，感谢提醒，我做了视频和截图。我会将这个 issue 的地址贴给对方看，希望一切不言自明。
另外我的脚本在 Greasy Fork 上所注明的许可证是 [WTFPL](http://www.wtfpl.net/about/)，你可以随意处理这个脚本。


https://github.com/Unintendedz/talk-to-gpt-4-mobile/assets/64687143/ac935bbd-ecea-4919-84dd-3d246ffb62fa


![screencapture-chat-openai-2023-06-05-17_04_26](https://github.com/Unintendedz/talk-to-gpt-4-mobile/assets/64687143/c75b772d-2d07-4b4b-aa39-fd2b70169a1e)

**Comment by adamlui** [comment]
A video showing 7:25 of whiteness does not prove your ridiculous claim OpenAI released a model with no rate limits. A screenshot of 30 replies with no timestamps proves nothiing, either. Bottom line, *all* OpenAI models impose rate limits (servers belong to billion dollar Microsoft corporation, no one there is so crazy to remove rate limits)

**Comment by onepisYa** [comment]
谢谢，我的脚本已经被删除了， 但是我将脚本放到了 [openuserjs/ GPT-4_mobile](https://openuserjs.org/scripts/onepisya/GPT-4_Mobile)。 如果可以的话，我希望能将我的代码合并到你的代码中。

另外我的说明也可以发给你，不为了任何利益，就是希望能更多的人能用上这个脚本。 然后你最好把 所有的 unlimited 字样删除掉，免得他像个圣母一样，到处发表我们是骗子的言论。

以下是我编写的文档。

---- 

> 如果你想要看中文文档，请往下滚动网页。


> If you want to view the Chinese document, please scroll down the webpage.

# Brief Explanation (EN)

__gpt-4 and gpt-4 mobile are exclusively available for `plus` users.__ If you don't have a plus account, don't download this script unless you're interested in the gpt-3.5 and gpt-3.5 mobile models.

You can use GPT-4 Mobile in the same way as you would use GPT-3.5.

"Enhance your conversations" with the gpt-4-mobile model using a userscript. You can achieve this by combining the resources available at `https://github.com/Unintendedz/talk-to-gpt-4-mobile` and `https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available`. By utilizing the Tampermonkey script, you can engage in conversations with the gpt-4-mobile model, removing the restriction of 25 messages every 3 hours, and set GPT-4 Mobile as the default model. Furthermore, the gpt-3.5 mobile option has also been incorporated.



Thank you to both authors for the majority of the code contributions.
- [talk-to-gpt-4-mobile](https://github.com/Unintendedz/talk-to-gpt-4-mobile)
- [chatgpt-is-gpt4-by-default-plus-only-available](https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available)




__My job in this script was simply to stitch together two scripts and make them work seamlessly together. However, if you need to use the two scripts separately, perhaps you can download each of them separately as well.__



---

> This project aims to optimize and improve the user experience of OpenAI's chat model, addressing **two main issues**:

**Default model selection**: This Tampermonkey script automatically sets the user's specified default chat model, eliminating the need to manually select a model every time a new conversation is started. Users can enhance their efficiency by setting a default model based on their own needs and preferences.

**Inclusion of mobile models**: This script enables users to utilize OpenAI's mobile models (such as GPT-4 Mobile v2) even on non-mobile devices. This expands the range of model options, allowing users to choose a more suitable model based on their network environment and computational capabilities.

This project is written in JavaScript and runs through the Tampermonkey extension, enabling convenient and efficient usage directly within the browser.

> Tips: GPT-4 and GPT-4 Mobile are available exclusively for Plus users.

> Tips: This tool also supports GPT-3.5 mobile.




# Differences between GPT-4 and GPT-4 Mobile V2

Here are some observations and speculations found online:

Some users have noticed that GPT-4 Mobile V2 is used when creating chats in mobile applications, and they believe that this version is not as intelligent as the original GPT-4.

A few users have noticed that this model is also labeled as GPT-3, leading them to suspect that this version might just be another replica of GPT-3.5.

There are users who view this as deceptive behavior. They believe that when creating conversations on both mobile and web platforms and selecting GPT-4, there are noticeable differences. They perceive it as a way to consume GPT-4 credits while actually using the GPT-3 model.

Some users have observed that GPT-4 Mobile V2 appears to lack a limiter, speculating that this might be similar to the advancements between the older and newer versions of GPT-3.

Others speculate that OpenAI may have managed to shrink the model while maintaining its performance, making it less costly to operate.

However, these are all user speculations and observations, as OpenAI has not provided any official explanations.

Reference link: [gpt4 vs gpt4 mobile v2](https://www.reddit.com/r/ChatGPT/comments/13s677b/gpt4_vs_gpt4_mobile_v2/?onetap_auto=true)


> Here is the table summarized by GPT-4.


| Number | Model Name           | Description                                     | Speed (0-100) | Inference Ability (0-100) | Simplicity (0-100) | Drawbacks                                    |
| ------ | -------------------- | ----------------------------------------------- | ------------- | ----------------------- | ------------------ | -------------------------------------------- |
| 1      | GPT-3.5 Mobile       | Fastest model, suitable for most daily tasks     | 100           | 60                      | 40                 | Suitable for daily tasks, limited inference capability for complex tasks |
| 2      | GPT-3.5              | Fast speed, suitable for most daily tasks        | 90            | 60                      | 40                 | Suitable for daily tasks, limited inference capability for complex tasks |
| 3      | GPT-4 Mobile         | Optimized model, better for innovative and advanced reasoning tasks | 80 | 100                     | 80                 | Slower speed, but strong inference capability  |
| 4      | GPT-4                | Most capable model, suitable for innovative and advanced reasoning tasks | 70 | 100                     | 80                 | Slower speed, but strong inference capability  |
| 5      | GPT-4 Browsing       | Experimental model that knows when and how to browse the internet | 60 | Unknown                 | Unknown            | Experimental model, effectiveness unknown     |
| 6      | GPT-4 Plugins        | Experimental model that knows when and how to use plugins | 50 | Unknown                 | Unknown            | Experimental model, effectiveness unknown     |



# Possible Issues

Due to modifications in some registered script information, it is possible that customers who installed the script early may encounter difficulties in updating. If you encounter this problem, clearing the project's cookies will enable you to update or reinstall this script.


# Contact me

- [my twitter](https://twitter.com/onepisya)

---


# 简单的说明（ZH）

**gpt-4 和 gpt-4 mobile 仅限 `plus` 用户使用。** 没有 plus 账号的别下这个脚本，除非你是冲着 gpt-3.5 和 gpt-3.5 mobile 模型来的。



通过使用用户脚本，您可以提升与 gpt-4-mobile 模型的对话体验。您可以将位于 `https://github.com/Unintendedz/talk-to-gpt-4-mobile` 和 `https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available` 的资源结合起来实现这一目标。通过利用 Tampermonkey 脚本，您可以与 gpt-4-mobile 模型进行 "对话"，消除每3小时25条消息的限制，并将 GPT-4 Mobile 设置为默认模型。此外，还包含了 gpt-3.5 mobile 选项。

感谢两位作者为大部分代码贡献而付出的努力。
- [talk-to-gpt-4-mobile](https://github.com/Unintendedz/talk-to-gpt-4-mobile)
- [chatgpt-is-gpt4-by-default-plus-only-available](https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available)

**我在这个脚本中的工作是简单的缝合了两个脚本让它们融洽的在一起工作，但是如果你需要使用两个脚本分别控制，那么也许你可以分别去下载这两个脚本。**

---


> 本项目旨在优化和改善OpenAI聊天模型的用户体验，**主要解决了以下两个问题**：

**默认的模型选择问题**：该油猴脚本能够自动设置用户指定的默认聊天模型，避免了每次启动新对话时都需要手动选择模型的麻烦。用户可以根据自己的需求和偏好设置默认模型，提高使用效率。

**添加移动模型的问题**：该脚本能够使用户在非移动设备上也能使用OpenAI发布的移动模型（如GPT-4 Mobile v2）。这增加了模型的选择范围，使用户可以根据自己的网络环境和计算能力选择更适合的模型。

此项目基于JavaScript编写，通过油猴（Tampermonkey）插件运行，可以直接在浏览器中使用，方便快捷。

> tips: gpt-4 和 gpt-4 mobile 仅限 plus 用户使用。

> tips: 本工具也支持式 gpt-3.5 mobile 



# 关于 GPT-4 和 GPT-4 mobile v2 之间的区别

以下是网上的一些观察和猜测：

有些用户发现在移动应用中创建聊天时会使用GPT-4 Mobile V2，他们认为这个版本并不像原版的GPT-4那样智能。

一些用户注意到这个模型也被标识为GPT-3，他们怀疑这个版本可能只是GPT-3.5的另一个复制品。

有用户认为这是一种欺诈行为，他们认为在手机上和在网页上新建对话时提出同样的问题，选择GPT-4，会看到明显的区别。他们认为这只是另一种消耗GPT-4信用的方式，实际上使用的是GPT-3模型。

也有用户观察到GPT-4 Mobile V2似乎没有限制器，他们猜测这可能与GPT-3的旧版和新版之间的进步类似。

另一些用户认为OpenAI可能已经设法使模型变小，同时保持模型的性能，这样运行起来就不会那么昂贵。

然而，这些都只是用户的猜测和观察，OpenAI尚未对此做出任何官方解释。

参考连接 [gpt4 vs gpt4 mobile v2](https://www.reddit.com/r/ChatGPT/comments/13s677b/gpt4_vs_gpt4_mobile_v2/?onetap_auto=true)


> 下面是 gpt-4 总结的表格

| 序号 | 模型名称                     | 描述                                            | 速度(0-100分) | 推理能力(0-100分) | 简洁度(0-100分) | 缺点                                        |
| ---- | ---------------------------- | ----------------------------------------------- | ------------- | ----------------- | --------------- | -------------------------------------------- |
| 1    | GPT-3.5 Mobile               | 最快的模型，适用于大部分日常任务                | 100           | 60                | 40              | 适用于日常任务，但对于复杂任务的推理能力有限 |
| 2    | GPT-3.5                      | 速度很快，适用于大部分日常任务                  | 90            | 60                | 40              | 适用于日常任务，但对于复杂任务的推理能力有限 |
| 3    | GPT-4 Mobile                 | 优化后的模型，对于需要创新和高级推理的任务更优  | 80            | 100               | 80              | 速度较慢，但推理能力强                      |
| 4    | GPT-4                        | 最有能力的模型，适合需要创新和高级推理的任务    | 70            | 100               | 80              | 速度较慢，但推理能力强                      |
| 5    | GPT-4 Browsing               | 知道何时如何浏览互联网的实验性模型              | 60            | 不明              | 不明            | 实验性模型，效果未知                        |
| 6    | GPT-4 Plugins                | 知道何时如何使用插件的实验性模型                | 50            | 不明              | 不明            | 实验性模型，效果未知                        |


# 可能出现的问题

因为修改一些脚本注册的信息，所以可能导致早期安装的客户无法更新，如果遇到此问题，清除本项目的cookie 即可更新或者重新安装此脚本。


# 联系我

- [我的推特](https://twitter.com/onepisya)

- 微信号 onepisYa


> 下面是我的微信 视频号，感兴趣的可以扫码关注。

> Here is my WeChat Video account. If you're interested, you can scan the code to follow me. If you use wechat.
---

![a](https://greasyfork.s3.us-east-2.amazonaws.com/6mxs7qjfr17gapz2jdsmn52oa0oi)

**Comment by adamlui** [comment]
> Please note that the intent of the script is to lift the GPT-4 limit of 25 entries in 3 hours. I found from your screenshot that you have not signed up for a Plus membership. So if you're not clear about that limitation, I understand.

You have falsely advertised the intent as "Make conversations unlimited" which does *not* occur for any model, Plus or no Plus, so you are a false advertiser.

> Even so, my intention is to share the power of this script with those who are bothered by the 25 records per hour limit of the GPT-4 model, not to deliberately deceive anyone.

If this were true, then you would not have deceived by falsely describing script as "Make conversations unlimited" (you obviously chose to do this to gain installs, but at the expense of wasting the time of users truly seeking unlimited conversations, very selfish tactic I must say)

> gpt-4-mobile has significantly higher capabilities than GPT-3.5, so my script is valuable,

GPT-4 Mobile does **not** "make conversations unlimited" as you've falsely claimed alone as the entire description, so your script is misleading

> I don't think my script deserves your violent replies and criticism.

I have done nothing violent (impossible over the Internet, violence requires physical contact)

> I need to stress the fact that I haven't hit any limits at all during hours of sustained high-intensity conversations.
For me, the number of GPT-4 MOBILE model messages is unlimited, and I don't think Unlimited is an excessive word.

You have done nothing to prove this false claim, instead releasing a script to the wild to gain installs by false advertising

> If you want to judge this word for word, that's your freedom.

Of course I'm free to judge false advertisers, I don't need your permission sir

**Comment by Unintendedz** [comment]
> > Please note that the intent of the script is to lift the GPT-4 limit of 25 entries in 3 hours. I found from your screenshot that you have not signed up for a Plus membership. So if you're not clear about that limitation, I understand.
> 
> You have falsely advertised the intent as "Make conversations unlimited" which does _not_ occur for any model, Plus or no Plus, so you are a false advertiser.
> 
> > Even so, my intention is to share the power of this script with those who are bothered by the 25 records per hour limit of the GPT-4 model, not to deliberately deceive anyone.
> 
> If this were true, then you would not have deceived by falsely describing script as "Make conversations unlimited" (you obviously chose to do this to gain installs, but at the expense of wasting the time of users truly seeking unlimited conversations, very selfish tactic I must say)
> 
> > gpt-4-mobile has significantly higher capabilities than GPT-3.5, so my script is valuable,
> 
> GPT-4 Mobile does **not** "make conversations unlimited" as you've falsely claimed alone as the entire description, so your script is misleading
> 
> > I don't think my script deserves your violent replies and criticism.
> 
> I have done nothing violent (impossible over the Internet, violence requires physical contact)
> 
> > I need to stress the fact that I haven't hit any limits at all during hours of sustained high-intensity conversations.
> > For me, the number of GPT-4 MOBILE model messages is unlimited, and I don't think Unlimited is an excessive word.
> 
> You have done nothing to prove this false claim, instead releasing a script to the wild to gain installs by false advertising
> 
> > If you want to judge this word for word, that's your freedom.
> 
> Of course I'm free to judge false advertisers, I don't need your permission sir

很高兴您能再次澄清您的观点，我理解人和人之间观念不一致是正常的。
既然如此，祝您生活愉快，不要为了虚假的广告商和欺骗安装量的家伙而动气。

**Comment by adamlui** [comment]
I'm not mad, I'm replying here because you link to it in my report of your script for violating rules on false advertising (so moderators can read)

**Comment by adamlui** [comment]
(and it doesn't take anger to report scripts that cheat, just vigilance)

**Comment by xcanwin** [comment]
这个叫@adamlui 的美国人喜欢消耗大家的技术研究时间，跑到我们（@onepisYa 、@Unintendedz 、@mefengl ）的项目里咬文嚼字发差评，大家可以礼尚往来。
https://greasyfork.org/zh-CN/scripts/462804-keepchatgpt/discussions/181544

1. 中国讲究礼尚往来，别人待我如朋友，我也待人如朋友。
2. 那个人是个阴阳人、双标人、美国人。他很过分，在本项目的反馈区刷差评，本来我不知道是他的，你让我研究冲突我就去看了他的github，我才知道原来是他在我这里刷差评。他真是一个阴阳怪气的家伙，代码写得那么烂，一个项目各种贴标签、logo显得自己多高大上。他为了贬低我的代码，在别人面前吹自己的代码多简洁，吹他的代码才70行，读过他代码的都知道多个链接相互引用，至少四五百行。不知道他想隐藏些什么，他这种调用外链的方式最容易引入后门了。不建议使用他写的东西。
3. 他在开源社区这种交流技术的地方搞这些贬低他人提升自己的东西，体现出他的没人品和阴阳怪气。
4. 他建了一个综合仓库，在里面写各个项目的代码。然后居然还为每个文件夹各自建一个仓库。最后每个新仓库居然还引用外链，链接的是他新建的仓库。他的目的就是提高别人审计他代码安全性的成本，方便加入恶意代码，真的太阴阳了。
5. 他还自建了awesome仓库，然后把自己的项目打上自建的awesome标签上，真的太阴阳了。
6. 最后强调，中国讲究礼尚往来。

**Comment by xcanwin** [comment]
大家多把时间花在技术提升上吧，多开源些好用的功能，空余时间可以陪陪他。

**Comment by Unintendedz** [comment]
> 谢谢，我的脚本已经被删除了， 但是我将脚本放到了 [openuserjs/ GPT-4_mobile](https://openuserjs.org/scripts/onepisya/GPT-4_Mobile)。 如果可以的话，我希望能将我的代码合并到你的代码中。
> 
> 另外我的说明也可以发给你，不为了任何利益，就是希望能更多的人能用上这个脚本。 然后你最好把 所有的 unlimited 字样删除掉，免得他像个圣母一样，到处发表我们是骗子的言论。
> 
> 以下是我编写的文档。
> 
> > 如果你想要看中文文档，请往下滚动网页。
> 
> > If you want to view the Chinese document, please scroll down the webpage.
> 
> # Brief Explanation (EN)
> **gpt-4 and gpt-4 mobile are exclusively available for `plus` users.** If you don't have a plus account, don't download this script unless you're interested in the gpt-3.5 and gpt-3.5 mobile models.
> 
> You can use GPT-4 Mobile in the same way as you would use GPT-3.5.
> 
> "Enhance your conversations" with the gpt-4-mobile model using a userscript. You can achieve this by combining the resources available at `https://github.com/Unintendedz/talk-to-gpt-4-mobile` and `https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available`. By utilizing the Tampermonkey script, you can engage in conversations with the gpt-4-mobile model, removing the restriction of 25 messages every 3 hours, and set GPT-4 Mobile as the default model. Furthermore, the gpt-3.5 mobile option has also been incorporated.
> 
> Thank you to both authors for the majority of the code contributions.
> 
> * [talk-to-gpt-4-mobile](https://github.com/Unintendedz/talk-to-gpt-4-mobile)
> * [chatgpt-is-gpt4-by-default-plus-only-available](https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available)
> 
> **My job in this script was simply to stitch together two scripts and make them work seamlessly together. However, if you need to use the two scripts separately, perhaps you can download each of them separately as well.**
> 
> > This project aims to optimize and improve the user experience of OpenAI's chat model, addressing **two main issues**:
> 
> **Default model selection**: This Tampermonkey script automatically sets the user's specified default chat model, eliminating the need to manually select a model every time a new conversation is started. Users can enhance their efficiency by setting a default model based on their own needs and preferences.
> 
> **Inclusion of mobile models**: This script enables users to utilize OpenAI's mobile models (such as GPT-4 Mobile v2) even on non-mobile devices. This expands the range of model options, allowing users to choose a more suitable model based on their network environment and computational capabilities.
> 
> This project is written in JavaScript and runs through the Tampermonkey extension, enabling convenient and efficient usage directly within the browser.
> 
> > Tips: GPT-4 and GPT-4 Mobile are available exclusively for Plus users.
> 
> > Tips: This tool also supports GPT-3.5 mobile.
> 
> # Differences between GPT-4 and GPT-4 Mobile V2
> Here are some observations and speculations found online:
> 
> Some users have noticed that GPT-4 Mobile V2 is used when creating chats in mobile applications, and they believe that this version is not as intelligent as the original GPT-4.
> 
> A few users have noticed that this model is also labeled as GPT-3, leading them to suspect that this version might just be another replica of GPT-3.5.
> 
> There are users who view this as deceptive behavior. They believe that when creating conversations on both mobile and web platforms and selecting GPT-4, there are noticeable differences. They perceive it as a way to consume GPT-4 credits while actually using the GPT-3 model.
> 
> Some users have observed that GPT-4 Mobile V2 appears to lack a limiter, speculating that this might be similar to the advancements between the older and newer versions of GPT-3.
> 
> Others speculate that OpenAI may have managed to shrink the model while maintaining its performance, making it less costly to operate.
> 
> However, these are all user speculations and observations, as OpenAI has not provided any official explanations.
> 
> Reference link: [gpt4 vs gpt4 mobile v2](https://www.reddit.com/r/ChatGPT/comments/13s677b/gpt4_vs_gpt4_mobile_v2/?onetap_auto=true)
> 
> > Here is the table summarized by GPT-4.
> 
> Number	Model Name	Description	Speed (0-100)	Inference Ability (0-100)	Simplicity (0-100)	Drawbacks
> 1	GPT-3.5 Mobile	Fastest model, suitable for most daily tasks	100	60	40	Suitable for daily tasks, limited inference capability for complex tasks
> 2	GPT-3.5	Fast speed, suitable for most daily tasks	90	60	40	Suitable for daily tasks, limited inference capability for complex tasks
> 3	GPT-4 Mobile	Optimized model, better for innovative and advanced reasoning tasks	80	100	80	Slower speed, but strong inference capability
> 4	GPT-4	Most capable model, suitable for innovative and advanced reasoning tasks	70	100	80	Slower speed, but strong inference capability
> 5	GPT-4 Browsing	Experimental model that knows when and how to browse the internet	60	Unknown	Unknown	Experimental model, effectiveness unknown
> 6	GPT-4 Plugins	Experimental model that knows when and how to use plugins	50	Unknown	Unknown	Experimental model, effectiveness unknown
> # Possible Issues
> Due to modifications in some registered script information, it is possible that customers who installed the script early may encounter difficulties in updating. If you encounter this problem, clearing the project's cookies will enable you to update or reinstall this script.
> 
> # Contact me
> * [my twitter](https://twitter.com/onepisya)
> 
> # 简单的说明（ZH）
> **gpt-4 和 gpt-4 mobile 仅限 `plus` 用户使用。** 没有 plus 账号的别下这个脚本，除非你是冲着 gpt-3.5 和 gpt-3.5 mobile 模型来的。
> 
> 通过使用用户脚本，您可以提升与 gpt-4-mobile 模型的对话体验。您可以将位于 `https://github.com/Unintendedz/talk-to-gpt-4-mobile` 和 `https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available` 的资源结合起来实现这一目标。通过利用 Tampermonkey 脚本，您可以与 gpt-4-mobile 模型进行 "对话"，消除每3小时25条消息的限制，并将 GPT-4 Mobile 设置为默认模型。此外，还包含了 gpt-3.5 mobile 选项。
> 
> 感谢两位作者为大部分代码贡献而付出的努力。
> 
> * [talk-to-gpt-4-mobile](https://github.com/Unintendedz/talk-to-gpt-4-mobile)
> * [chatgpt-is-gpt4-by-default-plus-only-available](https://greasyfork.org/zh-CN/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available)
> 
> **我在这个脚本中的工作是简单的缝合了两个脚本让它们融洽的在一起工作，但是如果你需要使用两个脚本分别控制，那么也许你可以分别去下载这两个脚本。**
> 
> > 本项目旨在优化和改善OpenAI聊天模型的用户体验，**主要解决了以下两个问题**：
> 
> **默认的模型选择问题**：该油猴脚本能够自动设置用户指定的默认聊天模型，避免了每次启动新对话时都需要手动选择模型的麻烦。用户可以根据自己的需求和偏好设置默认模型，提高使用效率。
> 
> **添加移动模型的问题**：该脚本能够使用户在非移动设备上也能使用OpenAI发布的移动模型（如GPT-4 Mobile v2）。这增加了模型的选择范围，使用户可以根据自己的网络环境和计算能力选择更适合的模型。
> 
> 此项目基于JavaScript编写，通过油猴（Tampermonkey）插件运行，可以直接在浏览器中使用，方便快捷。
> 
> > tips: gpt-4 和 gpt-4 mobile 仅限 plus 用户使用。
> 
> > tips: 本工具也支持式 gpt-3.5 mobile
> 
> # 关于 GPT-4 和 GPT-4 mobile v2 之间的区别
> 以下是网上的一些观察和猜测：
> 
> 有些用户发现在移动应用中创建聊天时会使用GPT-4 Mobile V2，他们认为这个版本并不像原版的GPT-4那样智能。
> 
> 一些用户注意到这个模型也被标识为GPT-3，他们怀疑这个版本可能只是GPT-3.5的另一个复制品。
> 
> 有用户认为这是一种欺诈行为，他们认为在手机上和在网页上新建对话时提出同样的问题，选择GPT-4，会看到明显的区别。他们认为这只是另一种消耗GPT-4信用的方式，实际上使用的是GPT-3模型。
> 
> 也有用户观察到GPT-4 Mobile V2似乎没有限制器，他们猜测这可能与GPT-3的旧版和新版之间的进步类似。
> 
> 另一些用户认为OpenAI可能已经设法使模型变小，同时保持模型的性能，这样运行起来就不会那么昂贵。
> 
> 然而，这些都只是用户的猜测和观察，OpenAI尚未对此做出任何官方解释。
> 
> 参考连接 [gpt4 vs gpt4 mobile v2](https://www.reddit.com/r/ChatGPT/comments/13s677b/gpt4_vs_gpt4_mobile_v2/?onetap_auto=true)
> 
> > 下面是 gpt-4 总结的表格
> 
> 序号	模型名称	描述	速度(0-100分)	推理能力(0-100分)	简洁度(0-100分)	缺点
> 1	GPT-3.5 Mobile	最快的模型，适用于大部分日常任务	100	60	40	适用于日常任务，但对于复杂任务的推理能力有限
> 2	GPT-3.5	速度很快，适用于大部分日常任务	90	60	40	适用于日常任务，但对于复杂任务的推理能力有限
> 3	GPT-4 Mobile	优化后的模型，对于需要创新和高级推理的任务更优	80	100	80	速度较慢，但推理能力强
> 4	GPT-4	最有能力的模型，适合需要创新和高级推理的任务	70	100	80	速度较慢，但推理能力强
> 5	GPT-4 Browsing	知道何时如何浏览互联网的实验性模型	60	不明	不明	实验性模型，效果未知
> 6	GPT-4 Plugins	知道何时如何使用插件的实验性模型	50	不明	不明	实验性模型，效果未知
> # 可能出现的问题
> 因为修改一些脚本注册的信息，所以可能导致早期安装的客户无法更新，如果遇到此问题，清除本项目的cookie 即可更新或者重新安装此脚本。
> 
> # 联系我
> * [我的推特](https://twitter.com/onepisya)
> * 微信号 onepisYa
> 
> > 下面是我的微信 视频号，感兴趣的可以扫码关注。
> 
> > Here is my WeChat Video account. If you're interested, you can scan the code to follow me. If you use wechat.
> 
> ![a](https://camo.githubusercontent.com/c2e5b07079c6cd4b97d37d14e19ff863453dfa67b0a0f294cb9c1ed8f1f49f09/68747470733a2f2f677265617379666f726b2e73332e75732d656173742d322e616d617a6f6e6177732e636f6d2f366d787337716a667231376761707a326a64736d6e35326f61306f69)

感谢，没想到人生中第一个 PR 竟然是在这种情况下迎来的。

在经过测试你的[脚本](https://openuserjs.org/scripts/onepisya/GPT-4_Mobile)之后，我认为能够默认切换 GPT-4 Mobile 是一个非常好的功能。

目前我希望功能尽量保持简单且符合直觉，对于 GPT-3.5 Mobile 我个人感觉可能展示”它的存在“的作用可能大于实际使用，不知道你怎么想？

进一步的内容我将在 PR 中和你交流，再次表示感谢！

**Comment by Unintendedz** [comment]
> 大家多把时间花在技术提升上吧，多开源些好用的功能，空余时间可以陪陪他。

确实，观念不同，把用在这种交流上耗费的时间拿来提升自己更划算。
顺便说一句，用过你的 KeepChatGPT，很棒的脚本。

**Comment by onepisYa** [comment]
> 这个叫@adamlui 的美国人喜欢消耗大家的技术研究时间，跑到我们（@onepisYa 、@Unintendedz 、@mefengl ）的项目里咬文嚼字发差评，大家可以礼尚往来。
> https://greasyfork.org/zh-CN/scripts/462804-keepchatgpt/discussions/181544
> 
> 1. 中国讲究礼尚往来，别人待我如朋友，我也待人如朋友。
> 2. 那个人是个阴阳人、双标人、美国人。他很过分，在我的项目的反馈区刷差评，本来我不知道是他的，网友让我研究冲突我就去看了他的github，我才知道原来是他在我的项目刷差评。他真是一个阴阳怪气的家伙，代码写得那么烂，一个项目各种贴标签、logo显得自己多高大上。他为了贬低我的代码，在别人面前吹自己的代码多简洁，吹他的代码才70行，读过他代码的都知道多个链接相互引用，至少四五百行。不知道他想隐藏些什么，他这种调用外链的方式最容易引入后门了。不建议使用他写的东西。
> 3. 他在开源社区这种交流技术的地方搞这些贬低他人提升自己的东西，体现出他的没人品和阴阳怪气。
> 4. 他建了一个综合仓库，在里面写各个项目的代码。然后居然还为每个文件夹各自建一个仓库。最后每个新仓库居然还引用外链，链接的是他新建的仓库。他的目的就是提高别人审计他代码安全性的成本，方便加入恶意代码，真的太阴阳了。
> 5. 他还自建了awesome仓库，然后把自己的项目打上自建的awesome标签上，真的太阴阳了。
> 6. 最后强调，中国讲究礼尚往来。
> 
> 

爱你，keepchatgpt 太好用了。这才是社区原本的样子。

**Comment by adamlui** [comment]
@xcanwin 

> This American named @adamlui likes to consume everyone's technical research time. He ran to our (@onepisYa, @Unintendedz, @mefengl) projects and sent bad reviews. Everyone can reciprocate.

I have never reviewed your script in my life, you are a terrible liar. I have indeed left honest reviews for the other 3 dishonest authors you have mentioned, because I do "like" exposing dishonest script authors.

> That man is a hermaphrodite, bipolar, American.

I am not a hermaphrodite, do you have problems with people who identify with both genders?

> He is too much. I posted negative comments in the feedback area of my project.

I have never posted feedback on your project before, however I did notice many others did whom you strangely accuse of being me (my Chinese is not good, how can I possibly be these honester reviewers who use perfect Chinese?) Stop being paranoid, just because people don't like your script doesn't mean everyone is me

> I didn’t know it was him. Netizens asked me to study conflicts, so I went to his github, and I realized that he was the one who posted negative comments on my project. 

I have never posted comments on your project, you are a liar. Link to your false claims or hold your silence.

> He is really a yin and yang guy, the code is so badly written, and the various labels and logos of a project make him look so tall.

How is my code badly written?

> In order to belittle my code, he brags how concise his code is in front of others.

When have I ever belittled your code? Please link to these strange false claims you keep repeating. But since you mention it, I just checked it out, it turns out it is indeed badly written! For example you mix & match template & string literals for no reason, also the strange indentation style would fail a default eslint config. So whoever the people are that belittle your code and you think are me, they are correct for a reason.

> His code is only 70 lines. Anyone who has read his code knows that multiple links refer to each other, at least four to five hundred lines. I don't know what he wants to hide. His way of calling external links is the easiest way to introduce backdoors. It is not recommended to use what he wrote.

Backdoors to what? Chatgpt.js is a trojan? With over 70000 monthly hits, approved by jsDelivr + Greasyfork? You make no sense...

> He engages in things that belittle others and improve himself in a place where technology is exchanged in the open source community, which shows his lack of character and eccentricity.

How did I belittle you? When have I ever commented on your code before today? Who is the one calling someone a hermaphrodite? Do you know what belittle means (also homophobia)

> He built a comprehensive warehouse and wrote the code of each project in it. Then actually build a warehouse for each folder. In the end, each new warehouse actually referenced the external link, and the link was his new warehouse. His purpose is to increase the cost for others to audit his code security, so as to facilitate the addition of malicious code, which is really too yin and yang.

It costs money to audit my code security?? This is news to me, also why do I have security policies to protect my thousands of users if I were a malicious actor? And can you specify what line of my open source code is malicious sir?

>  He also built the awesome warehouse by himself, and then marked his project with the self-built awesome label, which is really too yin and yang.

I did not build any Awesome warehouse (if you refer to awesome-userscripts it was built by a Google engineer, I am just a maintainer)

> Finally, he emphasized that China pays attention to courtesy and reciprocity.

I don't know what this means sir, but to close my reply, I will have to mention OpenAI actually stopped the Cloudflare checks and constant disconnectivity already, so KeepChatGPT is a placebo useless script that is bloated with almost 1000 lines of code that serve no real purpose, but if that's how you learn to make userscripts I can't stop you sir

**Comment by Unintendedz** [comment]
鉴于 issue 的评论开始变得有些失控，我将删除部分与此 issue 本身无关的评论并且锁定这个 issue，对此非常抱歉。
