### ISSUE TITLE
能否实现调用GPT-4 Mobile的API

### ISSUE THREAD

**Issue by Hiusam** [Unintendedz/talk-to-gpt-4-mobile#4]
作者您好！

感谢您提供如此优质的脚本。我想请问下如果能够在网页端使用GPT-4 mobile，是否技术上可以实现批量调用GPT-4 Mobile的API？我需要使用GPT-4 Mobile模型进行批量的数据处理。

如果您能提供相关资料或者开源项目，不胜感谢！

谢谢。

**Comment by Unintendedz** [comment]
官方客户端的 API 一个账号同一时间只允许传输一个响应，同时发起多个 conversation 会返回 429 错误：
```
{
    "detail": "Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."
}
```
所以我个人认为是不能批量调用 GPT-4 Mobile 的 API 了，除非你使用多个账号。

**Comment by Hiusam** [comment]
不好意思没有表达清楚，不需要同时传输多个响应，只需要自动化进行api调用，接受返回值就可以。

**Comment by Unintendedz** [comment]
> 不好意思没有表达清楚，不需要同时传输多个响应，只需要自动化进行api调用，接受返回值就可以。

那应该是可以实现的，但是直接调用官方 web 客户端的 API 你需要找到办法绕过 CF，我不记得 iOS 客户端需不需要。
